apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: 2401116
type: Opaque
data:
  username: ZGlldF9hcHA=        # base64("diet_app")
  password: c2VqYWwxMjM=        # base64("sejal123")
