apiVersion: v1
kind: Service
metadata:
  name: lowpoceat-service
spec:
  type: NodePort
  selector:
    app: lowpoceat
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
